In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4143, 5814, 7281, 4084],
 [4143, 5814, 7281, 3504],
 [4143, 1595, 7281, 9617],
 [1604, 6095, 1344, 6939, 3056],
 [1604, 6095, 1344, 6939, 9986],
 [8185, 4143, 2696, 7281, 7760],
 [4666, 9696, 8668, 6939]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4143 5814 7281 4084]
 [   0    0    0    0 4143 5814 7281 3504]
 [   0    0    0    0 4143 1595 7281 9617]
 [   0    0    0 1604 6095 1344 6939 3056]
 [   0    0    0 1604 6095 1344 6939 9986]
 [   0    0    0 8185 4143 2696 7281 7760]
 [   0    0    0    0 4666 9696 8668 6939]]


In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 1s 928ms/step


array([[[-0.02741781, -0.00368531, -0.04334382, -0.0352881 ,
          0.02506551, -0.02896937, -0.02839819,  0.04644016,
          0.02381955,  0.02115223],
        [-0.02741781, -0.00368531, -0.04334382, -0.0352881 ,
          0.02506551, -0.02896937, -0.02839819,  0.04644016,
          0.02381955,  0.02115223],
        [-0.02741781, -0.00368531, -0.04334382, -0.0352881 ,
          0.02506551, -0.02896937, -0.02839819,  0.04644016,
          0.02381955,  0.02115223],
        [-0.02741781, -0.00368531, -0.04334382, -0.0352881 ,
          0.02506551, -0.02896937, -0.02839819,  0.04644016,
          0.02381955,  0.02115223],
        [-0.00305405, -0.00220851, -0.01215578,  0.04919278,
         -0.03290396, -0.0001798 ,  0.02396114,  0.02805964,
         -0.01227794,  0.00861007],
        [ 0.0137957 , -0.02899054, -0.0229085 ,  0.04877837,
          0.03649292,  0.03538008, -0.04795067,  0.00380983,
         -0.03019408,  0.01403644],
        [ 0.04532589, -0.01823587,  0.04901861,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4143, 5814, 7281, 4084])